name: Release new versions

on:
  push:
    tags:
      - 'v*.*.*'

# Permissions are required to add the provenance signature to the package
permissions:
  contents: read
  packages: write

jobs:
  publish-lib:
    name: Publish @renderize/lib to npm registry
    runs-on: ubuntu-latest

    # Permissions are required to add the provenance signature to the package
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          corepack: true
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Publish  @enclosed/lib to npm
        run: pnpm publish --access public --no-git-checks
        env:
          NPM_CONFIG_PROVENANCE: true
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
